name: ⚙️ Build prerender
on:
  pull_request:

jobs:
  prerender:
    name: prerender
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build demo by prerender
        run: npx nx build-gh-pages demo

concurrency:
  group: build-prerender-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
