name: ⚙️ Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.56.3
      - uses: taiga-family/ci/actions/setup/node@v1.56.3
      - run: npm run run-many:build:libs

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
