name: ⚙️ Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: npm run run-many:build:libs

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
