name: ⚙️ Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build demo
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.65.1
      - uses: taiga-family/ci/actions/setup/node@v1.65.1
      - run: npx nx build demo

concurrency:
  group: build-demo-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
