name: ⚙️ Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.79.0
      - uses: taiga-family/ci/actions/setup/node@v1.79.0
      - run: npx nx run-many -t build --exclude demo

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
