name: ⚙️ Build prerender
on:
  pull_request:

jobs:
  prerender:
    name: Build prerender
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: taiga-family/ci/actions/setup/node@v1.50.5
      - run: npx nx build-gh-pages demo

concurrency:
  group: build-prerender-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
