name: ⚙️ Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: |
          npm run prettier -- --check
          npm run typecheck
          npm run lint

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
