name: ⚠️ Release
on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.73.1
      - uses: taiga-family/ci/actions/run/release-it@v1.73.1
        with:
          ref: ${{ github.ref }}
          githubToken: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          npmToken: ${{ secrets.NPM_TOKEN }}
          mode: ${{ github.event.inputs.mode }}
          forcePush: true

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
