name: ⚠️ Release @ng-web-apis
on:
  workflow_dispatch:
    inputs:
      forcePush:
        type: boolean
        required: false
        description: --force-publish all package
      mode:
        type: choice
        description: force all packages to be versioned (depend --force-publish)
        required: false
        default: minor
        options:
          - patch
          - minor
          - major

jobs:
  run-release:
    name: Run release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
    steps:
      - name: Fetch from origin repo
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - uses: taiga-family/ci/actions/setup/node@v1.48.0
      - uses: taiga-family/ci/actions/setup/config/git@v1.48.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/config/npm@v1.48.0
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Lerna update version of packages
        if: always()
        run: |
          if [[ ${{ github.event.inputs.forcePush }} == "true" ]]; then
            npx lerna version ${{ github.event.inputs.mode }} --no-private --force-publish
          else
              npx lerna version --no-private
          fi

      - run: npx nx run-many --target=build --parallel=1 --output-style=stream --exclude=demo

      - run: npx nx run-many --target=publish --parallel=1 --output-style=stream
        if: always()

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
