name: ⚙️ Unit tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.62.24
      - uses: taiga-family/ci/actions/setup/node@v1.62.24
      - run: npx nx run-many -t=test

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
