name: ⚙️ Unit tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [common]
    name: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run tests for ${{ matrix.project }}
        run: npx nx test ${{ matrix.project }}

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage-${{ github.workflow }}-${{ github.run_id }}
          path: coverage

  codecov:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/download-artifact@v3.0.2
        with:
          name: coverage-${{ github.workflow }}-${{ github.run_id }}
          path: coverage

      - name: Display structure of coverage files
        run: tree -L 2 ./coverage -P 'lcov.info'

      - uses: codecov/codecov-action@v3.1.3
        with:
          directory: ./coverage/common/
          flags: summary,common
          name: kit

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
